# image will be published to ghcr.io/<user>/<name>
name: formile-desktop-ublue
# description will be included in the image's metadata
description: This is my personal OS image close to vanila ublue build.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # - type: files
  #   files:
  #     - services: /etc/systemd/system
  #     - usr: /usr
  #     - hwdb: /etc/udev/hwdb.d/
  #     # copies config/files/usr into your image's /usr.
      # put configuration files you want in /etc/ on a booted system 
      # in /usr/etc/ in the image. read more in files module reference.

  # - type: akmods
  #   base: main
  #   install:
  #     - xone
  #     - openrazer

  - type: rpm-ostree
    repos:
    - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/repo/fedora-%OS_VERSION%/kylegospo-bazzite-fedora-%OS_VERSION%.repo 
    # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    # - https://download.opensuse.org/repositories/hardware:/razer/Fedora_%OS_VERSION%/hardware:razer.repo
    install:
      # - openrazer-meta
      - podman-compose
      # - joystickwake
      # - zerotier-one
      # - evtest
      # - micro
      # - starship
    remove:
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: script
    scripts:
    - zerotier.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
